# Generated by Django 2.0.7 on 2018-08-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('inscricaoestadual', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.IntegerField(default=0)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.IntegerField(default=0)),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('descricao', models.CharField(max_length=500)),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galeria')),
                ('descricao', models.TextField()),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criado', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crrt.Cliente')),
                ('produto', models.ManyToManyField(to='crrt.Produto')),
            ],
        ),
    ]
